### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by olehlong** [DerelictOrg/DerelictLua#6]
Hello. Does anyone have a working example? I'm trying to run a basic program but it throws a segfault. Here's my code:
```
import std.stdio;
import derelict.lua.lua;
import std.file;

void main() {
	lua_State* state = luaL_newstate();
	luaL_openlibs(state);
	
	scope(exit) {
		lua_close(state);
	}
	
	string fileCont = readText("test.lua");
	writeln(fileCont);
	
	luaL_loadstring(state, fileCont.ptr);
}
```
Segfault happens at luaL_newstate.

Versions:
Lua 5.2.3
DMD 2.067.0

Is it possible that binding is incompatible with Lua 5.2.3?

**Comment by aldacron** [comment]
As the README says, you need to call DerelictLua.load() before attempting to call any Lua functions. All of the Derelict bindings are dynamic bindings. This means they load the shared libraries manually, which is why you don't have to link with Lua when you compile. Just make sure that the Lua shared libraries are installed on your system (or in the executable directory on Windows). See http://derelictorg.github.io/using.html for more info.

**Comment by olehlong** [comment]
Oh, sorry, it was dumb of me, I thought I have load. Thank you.
